path: 'Documents/GitHub/pothole_amith_dsml/dataset_pothole/data'
train: 'Documents/GitHub/pothole_amith_dsml/dataset_pothole/data/images/train'
val: 'Documents/GitHub/pothole_amith_dsml/dataset_pothole/data/images/val'

# Classes
names:
 0: pothole