path: '/Users/amithmg/Documents/GitHub/pothole_amith_dsml/dataset_pothole/data'
train: '/Users/amithmg/Documents/GitHub/pothole_amith_dsml/dataset_pothole/data/images/train'
val: '/Users/amithmg/Documents/GitHub/pothole_amith_dsml/dataset_pothole/data/images/val'

# Classes
names:
 0: pothole